Streamlined preparation for Hello, World!
EdgeNet-project/edgenet-project.github.io pull request #5
Opened 2018-07-31 14:30 UTC by timur-friedman

In this rewrite of the tutorial preparation, we tell the user ahead of time what he/she will be doing. Also, much of the Read Ahead of Time reading goes to Suggested Additional Reading at the end. And also, the node.js and kubectrl downloads are no longer optional, as they are what the tutorial uses. A user who is sophisticated enough to dispense with them will know that he/she may do so without us saying so.

2018-08-03 00:55 UTC, rickmcgeer requested changes
(1) I think they really should have read the Using EdgeNet tutorial
(2) I'm personally grateful for an install-these software suites upfront in tutorials, since it avoids nasty surprises later (similar to an ingredients list at the start of a recipe).  You're right, kubectl should be added to this list.  Actually, I see you have that in Install software...

2018-08-03 00:57 UTC, rickmcgeer approved these changes
Actually, as I re-read this, I simply missed how you reorganized it.  Sorry!  I'll just approve and merge.

2018-08-07 13:49 UTC, aaaaalbert commented
Sorry, I overlooked that this PR wasn't merged when I worked on the tutorial. I'll port @timur-friedman's changes over manually.

2018-08-07 16:47 UTC, aaaaalbert commented
I've manually merged the relevant bits from this PR to `master` in 8a7b6de15481cc3e48d38da3b3e9a2bcfabd73cd. Closing this PR. Thanks for contributing @timur-friedman!

2018-08-07 16:47 UTC, closed without merging